name: picupe38

channels:
  - defaults
  - conda-forge
  - anaconda
  - numba

dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - pyopengl
  - simbody
  - typing_extensions
  - jupyter
  - pythonnet
  - numba
  - pip
  - pip:
    - opencv-python